/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package incidentrecorder;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Shellback Software
 */
public class RecorderGUI extends javax.swing.JFrame {

    /**
     * Creates new form RecorderGUI
     */
    public RecorderGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        TimestampNotice = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        NotesLabel = new javax.swing.JLabel();
        NotesScrollPane = new javax.swing.JScrollPane();
        NotesField = new javax.swing.JTextArea();
        SaveButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        LocationLabel = new javax.swing.JLabel();
        LocationField = new javax.swing.JTextField();
        SubjectLabel = new javax.swing.JLabel();
        SubjectScrollPane = new javax.swing.JScrollPane();
        SubjectField = new javax.swing.JTextArea();
        PlateNumLabel = new javax.swing.JLabel();
        PlateNumField = new javax.swing.JTextField();
        PlateStateField = new javax.swing.JTextField();
        PlateStateLabel = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Incident Recorder");
        setMaximumSize(new java.awt.Dimension(353, 762));
        setMinimumSize(new java.awt.Dimension(353, 762));
        setPreferredSize(new java.awt.Dimension(353, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(353, 800));

        TimestampNotice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TimestampNotice.setText("<html>Time stamps are automatically <br/> saved when the Save button is pressed.</html>");

        NameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NameLabel.setText("Your Name:");

        NameField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        NotesLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NotesLabel.setText("Extra Notes:");

        NotesField.setColumns(20);
        NotesField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        NotesField.setLineWrap(true);
        NotesField.setRows(5);
        NotesField.setWrapStyleWord(true);
        NotesField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if(e.getKeyCode() == KeyEvent.VK_TAB) {
                    if(e.getModifiers() > 0) {
                        NotesField.transferFocusBackward();
                    } else {
                        NotesField.transferFocus();
                    }
                    e.consume();
                }
            }
        });
        NotesField.setDragEnabled(true);
        NotesField.setMinimumSize(new java.awt.Dimension(85, 21));
        NotesField.setPreferredSize(new java.awt.Dimension(300, 89));
        NotesScrollPane.setViewportView(NotesField);

        SaveButton.setText("Save");
        SaveButton.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if(e.getKeyCode() == KeyEvent.VK_ENTER) {
                    saveButtonPressed();
                    e.consume();
                }
            }
        });
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        ClearButton.setText("Clear All");
        ClearButton.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if(e.getKeyCode() == KeyEvent.VK_ENTER) {
                    clearButtonPressed();
                    e.consume();
                }
            }
        });
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        LocationLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LocationLabel.setText("Location:");

        LocationField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LocationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationFieldActionPerformed(evt);
            }
        });

        SubjectLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SubjectLabel.setText("Subject Description:");

        SubjectField.setColumns(20);
        SubjectField.setLineWrap(true);
        SubjectField.setRows(5);
        SubjectField.setWrapStyleWord(true);
        SubjectField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if(e.getKeyCode() == KeyEvent.VK_TAB) {
                    if(e.getModifiers() > 0) {
                        SubjectField.transferFocusBackward();
                    } else {
                        SubjectField.transferFocus();
                    }
                    e.consume();
                }
            }
        });
        SubjectScrollPane.setViewportView(SubjectField);

        PlateNumLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PlateNumLabel.setText("Lic. Plate #:");

        PlateNumField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PlateNumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlateNumFieldActionPerformed(evt);
            }
        });

        PlateStateField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PlateStateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlateStateFieldActionPerformed(evt);
            }
        });

        PlateStateLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PlateStateLabel.setText("Lic. Plate State:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(SaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(PlateStateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PlateStateField))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(NameLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LocationLabel)
                                        .addGap(26, 26, 26)
                                        .addComponent(LocationField, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(SubjectScrollPane, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TimestampNotice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                        .addComponent(NotesScrollPane, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(NotesLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SubjectLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PlateNumLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(PlateNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TimestampNotice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LocationField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubjectLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubjectScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlateNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlateNumField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlateStateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlateStateField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NotesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NotesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        SaveButton.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /* 
    *   Save the notes then clear the box
    */
    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        saveButtonPressed();
    }//GEN-LAST:event_SaveButtonActionPerformed

    /* 
    *  Actual save logic, allows for use of enter key
    */
    private void saveButtonPressed() {
        // Parse the current time + date. Use the time in the log, date as the filename
        LocalDateTime curDateTime = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HHmm");
        String fmtDateTime = curDateTime.format(formatter);
        String[] fullDateTime = fmtDateTime.split(" ");
        String date = fullDateTime[0];
        String time = fullDateTime[1];
        IncidentRecorder rec = new IncidentRecorder(date, time, NotesField.getText().trim(), 
            NameField.getText().trim(), LocationField.getText().trim(), SubjectField.getText().trim(), 
            PlateNumField.getText().trim(), PlateStateField.getText().trim());
        rec.saveFile();
        clearButtonPressed();
    }
    
    
    /* 
    *   Actual clear logic, allows for use of enter key 
    */
     private void clearButtonPressed() {
        //ClearButton.
        NotesField.setText("");
        NameField.setText("");
        LocationField.setText("");
        SubjectField.setText("");
        PlateNumField.setText("");
        PlateStateField.setText("");
        NameField.requestFocus();
    } 
    
    /* 
    *   Clears the notes field 
    */
    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        clearButtonPressed();
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void LocationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationFieldActionPerformed

    private void PlateNumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlateNumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlateNumFieldActionPerformed

    private void PlateStateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlateStateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlateStateFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecorderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecorderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecorderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecorderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecorderGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearButton;
    private javax.swing.JTextField LocationField;
    private javax.swing.JLabel LocationLabel;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextArea NotesField;
    private javax.swing.JLabel NotesLabel;
    private javax.swing.JScrollPane NotesScrollPane;
    private javax.swing.JTextField PlateNumField;
    private javax.swing.JLabel PlateNumLabel;
    private javax.swing.JTextField PlateStateField;
    private javax.swing.JLabel PlateStateLabel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JTextArea SubjectField;
    private javax.swing.JLabel SubjectLabel;
    private javax.swing.JScrollPane SubjectScrollPane;
    private javax.swing.JLabel TimestampNotice;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
